# Generated by Django 4.0.6 on 2022-07-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_option_optionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='product.option'),
            preserve_default=False,
        ),
    ]
