# Generated by Django 4.0.6 on 2022-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_content_de_product_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='title_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
